### ISSUE TITLE
Support for OneDrive for Business

### ISSUE THREAD

**Issue by jmkao** [Tekki/onedrive-perl#1]
I have hooked up a OneDrive for Business account and successfully authenticated. The first time I try to synchronize into the destination directory results in the following error:

```
72 new tasks downloaded

1: root
DBD::SQLite::st execute failed: NOT NULL constraint failed: item.modifiedby at /usr/local/src/onedrive-perl/script/../lib/Tekki/Onedrive/Database.pm line 57.
 at /usr/local/src/onedrive-perl/script/../lib/Tekki/Onedrive/Database.pm line 57.
```

**Comment by Tekki** [comment]
As you can read in the readme, support for OneDrive for Business is the next step but one. Items from Business have a different structure and are not yet processed correctly.

**Comment by jmkao** [comment]
I see. Are you open to having an outside contributor help out on this? I have some perl programming ability and access to an affected account. From your response, my understanding is that the `item` table in such an account has a different columns than in a personal account. Anything else that you might already have discovered that would be helpful if you're okay with it?

**Comment by Tekki** [comment]
Of course, any help is appreciated. The first things we need are tests. This means the same set of tests we have for Personal should be available for Business.
For the moment, it's too early to edit the code, it will change fundamentally with the implementation of remote items.
Ah yes, and I think we need an implementation of the QuickXorHash (https://gist.github.com/rgregg/c07a91964300315c6c3e77f7b5b861e4). This is used in Business instead of SHA1 and CRC32. If you're interested in taking a look at it, please open another issue.

**Comment by Tekki** [comment]
@jmkao, another question: Do you have access to SharePoint libraries too?

**Comment by jmkao** [comment]
Let me take a look at the QuickXorHash, that seems reasonably doable. I think I may have access to SharePoint libraries that I can share into OneDrive, but need to check.

**Comment by Tekki** [comment]
You can try again, but please reset your connection as described at the beginning of the README.

For the QuickXorHash, I've opened issue #2.

**Comment by Tekki** [comment]
Waiting for feedback.
